
dsAudio:
    Type: source
    Name: dsAudio_1_port

    # Profile for L1
    features:
        extendedEnumsSupported: false

    # dsAUDIOPORT_TYPE_ID_LR       = 0x00,  ///< RCA audio output
    # dsAUDIOPORT_TYPE_HDMI        = 0x01,  ///< HDMI audio output
    # dsAUDIOPORT_TYPE_SPDIF       = 0x02,  ///< SPDIF audio output
    # dsAUDIOPORT_TYPE_SPEAKER     = 0x03,  ///< SPEAKER audio output
    # dsAUDIOPORT_TYPE_HDMI_ARC    = 0x04,  ///< HDMI ARC/EARC audio output
    # dsAUDIOPORT_TYPE_HEADPHONE   = 0x05,  ///< Headphone jack
    # dsAUDIOPORT_TYPE_MAX         = 0x06   ///< Out of range
    PortTypes:
      - 0x00 # ID_LR
      - 0x01 # HDMI
      - 0x02 # SPDIF

    # Number of supported ports
    Number_of_supported_ports: 1

    # dsAUDIOSUPPORT_NONE             = 0x0,     ///< None
    # dsAUDIOSUPPORT_ATMOS            = 0x01,    ///< Dolby Atmos
    # dsAUDIOSUPPORT_DD               = 0x02,    ///< Dolby Digitial
    # dsAUDIOSUPPORT_DDPLUS           = 0x04,    ///< Dolby Digital Plus
    # dsAUDIOSUPPORT_DAD              = 0x08,    ///< Digital Audio Delivery
    # dsAUDIOSUPPORT_DAPv2            = 0x10,    ///< Digital Audio Processing version 2
    # dsAUDIOSUPPORT_MS12             = 0x20,    ///< Multi Stream 12
    # dsAUDIOSUPPORT_MS12V2           = 0x40,    ///< Multi Stream Version 2
    # dsAUDIOSUPPORT_Invalid          = 0x80,    ///< Invalid
    Audio_Capabilities: 0x37  # dsAUDIOSUPPORT_ATMOS | dsAUDIOSUPPORT_DAPv2 | dsAUDIOSUPPORT_MS12 | dsAUDIOSUPPORT_DD | dsAUDIOSUPPORT_DDPLUS

    # Number of supported Audio Codecs
    Number_of_Supported_Codecs: 8

    # dsAUDIO_FORMAT_NONE                   = 0x00,     ///< No audio format
    # dsAUDIO_FORMAT_PCM                    = 0x01,     ///< Pulse-code Modulation audio format
    # dsAUDIO_FORMAT_DOLBY_AC3              = 0x02,     ///< Audio Compression 3 audio format
    # dsAUDIO_FORMAT_DOLBY_EAC3             = 0x03,     ///< Enhance Audio Compression 3 audio format
    # dsAUDIO_FORMAT_DOLBY_AC4              = 0x04,     ///< Audio Compression 4 audio format
    # dsAUDIO_FORMAT_DOLBY_MAT              = 0x05,     ///< Metadata-enhanced Audio Transmission audio format
    # dsAUDIO_FORMAT_DOLBY_TRUEHD           = 0x06,     ///< Dolby TrueHD audio format
    # dsAUDIO_FORMAT_DOLBY_EAC3_ATMOS       = 0x07,     ///< Audio Compression 3 Dolby Atmos audio format
    # dsAUDIO_FORMAT_DOLBY_TRUEHD_ATMOS     = 0x08,     ///< Dolby TrueHD Dolby Atmos audio format
    # dsAUDIO_FORMAT_DOLBY_MAT_ATMOS        = 0x09,     ///< Metadata-enhanced Audio Transmission Dolby Atmos audio format
    # dsAUDIO_FORMAT_DOLBY_AC4_ATMOS        = 0x0A,     ///< Audio Compression 4 Dolby Atmos audio format
    # dsAUDIO_FORMAT_AAC                    = 0x0B,     ///< Advanced Audio Coding
    # dsAUDIO_FORMAT_VORBIS                 = 0x0C,     ///< Vorbis sound audio format
    # dsAUDIO_FORMAT_WMA                    = 0x0D,     ///< Windows Media audio format
    # dsAUDIO_FORMAT_UNKNOWN                = 0x0E,     ///< Unknown audio format
    # dsAUDIO_FORMAT_MAX                    = 0x0F      ///< Out of range
    supportedCodecs:
     - 0x01     # dsAUDIO_FORMAT_PCM
     - 0x02     # dsAUDIO_FORMAT_DOLBY_AC3
     - 0x03     # dsAUDIO_FORMAT_DOLBY_EAC3
     - 0x04     # dsAUDIO_FORMAT_DOLBY_AC4
     - 0x07     # dsAUDIO_FORMAT_DOLBY_EAC3_ATMOS
     - 0x0A     # dsAUDIO_FORMAT_DOLBY_AC4_ATMOS
     - 0x0B     # dsAUDIO_FORMAT_AAC
     - 0x0C     # dsAUDIO_FORMAT_VORBIS

    # Port details
    Ports:
        # Port Number to parse the port details
        1:
            # dsAUDIOPORT_TYPE_ID_LR       = 0x00,       ///< RCA audio output
            # dsAUDIOPORT_TYPE_HDMI        = 0x01,       ///< HDMI audio output
            # dsAUDIOPORT_TYPE_SPDIF       = 0x02,       ///< SPDIF audio output
            Typeid: 0x01  # HDMI
            Name: "HDMI"
            # An index value used to access a specific port within an array of ports with the same type.
            Index: 0
            # number of supported compressions
            number_of_supported_compressions: 4
            # dsAUDIO_CMP_NONE   = 0x00, ///< No audio compression.
            # dsAUDIO_CMP_LIGHT  = 0x01, ///< Light audio level compression.
            # dsAUDIO_CMP_MEDIUM = 0x02, ///< Medium audio level compression.
            # dsAUDIO_CMP_HEAVY  = 0x03, ///< Heavy audio level compression.
            compressions: [0x00, 0x01, 0x02, 0x03]  # NONE, LIGHT, MEDIUM, HEAVY
            # Number of supported Stereo modes
            number_of_supported_stereo_modes: 3
            # dsAUDIO_STEREO_UNKNOWN                   = 0x00,  ///< Stereo mode none
            # dsAUDIO_STEREO_MONO                      = 0x01,  ///< Mono mode
            # dsAUDIO_STEREO_STEREO                    = 0x02,  ///< Normal stereo mode (L+R)
            # dsAUDIO_STEREO_SURROUND                  = 0x03,  ///< Surround mode
            # dsAUDIO_STEREO_PASSTHRU                  = 0x04,  ///< Passthrough mode
            stereo_modes: [0x02, 0x03, 0x04]  # STEREO, SURROUND, PASSTHRU
            stereo_auto_mode: true
            # dsMS12SUPPORT_NONE = 0x0,                        ///< MS12 Supported None
            # dsMS12SUPPORT_DolbyVolume = (1 << 0),            ///< MS12 supported Dolby Volume
            # dsMS12SUPPORT_InteligentEqualizer = (1 << 1),    ///< MS12 supported Intelligent Equalizer
            # dsMS12SUPPORT_DialogueEnhancer = (1 << 2),       ///< MS12 Dialogue Enhancer supported
            # dsMS12SUPPORT_Volumeleveller   = (1 << 3),       ///< MS12 Volume leveller
            # dsMS12SUPPORT_BassEnhancer     = (1 << 4),       ///< MS12 Bass Enhancer
            # dsMS12SUPPORT_SurroundDecoder  = (1 << 5),       ///< MS12 Surround Decoder
            # dsMS12SUPPORT_DRCMode          = (1 << 6),       ///< MS12 DRC Mode
            # dsMS12SUPPORT_SurroundVirtualizer = (1 << 7),    ///< MS12 Surround Virtualizer
            # dsMS12SUPPORT_MISteering       = (1 << 8),       ///< MS12 MI Steering
            # dsMS12SUPPORT_GraphicEqualizer = (1 << 9),       ///< MS12 Graphic equalizer
            # dsMS12SUPPORT_LEConfig         = (1 << 10),      ///< MS12 LE config
            # dsMS12SUPPORT_Invalid = (1 << 31)                ///< Invalid / Out of range
            MS12_Capabilities: 0x4D  # DolbyVolume | DialogueEnhancer | Volumeleveller | DRCMode
            MS12_AudioProfiles:
            # number of counts from the "ms12_audio_profiles.ini" file
            MS12_AudioProfileCount: 0
            IsMS12Decode: true
            IsMS11Decode: false
            # dsAUDIO_ATMOS_NOTSUPPORTED               = 0x00,  ///< ATMOS audio not supported
            # dsAUDIO_ATMOS_SUPPORTED                  = 0x01,  ///< ATMOS audio supported
            ATMOS_Capabilities: 0x01  # dsAUDIO_ATMOS_SUPPORTED
            dialog_enhancement_level:
                min: 0
                max: 12

